### ISSUE TITLE
Incorrect branch name in sync instructions

### ISSUE THREAD

**Issue by the-gobleo-tinkerer** [LangProc/langproc-2022-lab#1]
Hi! The following part in the readme refers to a `master` branch, but this repo has `main` instead:

https://github.com/LangProc/langproc-2022-lab/blob/ac72068f732f24bfec2bae56a56ac2896534f9cb/readme.md?plain=1#L144-L147

**Comment by johnwickerson** [comment]
Thanks! https://github.com/LangProc/langproc-2022-lab/commit/378853385a52e1eb4a23d471825cec91ccba7918
